# Permalinks
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM

safe: true
lsi: false

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
paginate:         1
baseurl:          http://bathtub.github.io/poole/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
