
# Permalinks
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM
  enable_coderay: true
  coderay_css: style
  coderay_wrap:              div
  coderay_line_numbers:      nil

safe: true
lsi: false

# Setup
title:            Poole
tagline:          The Jekyll Butler
paginate:         1
baseurl:          http://bathtub.github.io/poole/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
